kind: kcli_params
metadata:
  name: demo
tag: 4.20
version: stable
ctlplanes: 1
workers: 2
pool: default
network_type: OVNKubernetes
pull_secret: openshift_pull.json
ctlplane_memory: 32768
worker_memory: 16384
disk_size: 50
vmrules:
  - ^.*ctlplane.*:
      nets:
        - name: default
        - name: leafocp-node
          ip: 192.168.11.3
          gateway: 192.168.11.1
          netmask: 24
  - fedecluster-worker-0:
      nets:
        - name: default
        - name: leafocp-node
          ip: 192.168.11.4
          gateway: 192.168.11.1
          netmask: 24
  - fedecluster-worker-1:
      nets:
        - name: default
        - name: leafocp-node
          ip: 192.168.11.5
          gateway: 192.168.11.1
          netmask: 24
